### ISSUE TITLE
[Bug] Only first 100 entries are transformed

### ISSUE THREAD

**Issue by connor-baer** [contentful/migration-cli#82]
Hello 👋 

I’m running into an issue when using the `transformEntries()` method on a large number of entries. Only the first 100 entries are transformed. I assume this is due to the paginated response from the management API with a default limit of 100.

@stefanjudis has pointed me to https://github.com/contentful/migration-cli/blob/master/src/lib/fetcher.ts#L26-L29, so I'll give it a shot and make a PR.

**Comment by zcei** [comment]
Hej @connor-baer, we stumbled across the same thing a few days ago 🤦‍♂️ 
@Khaledgarbaya wanted to work on this as well, maybe he can sync with you here.

**Comment by connor-baer** [comment]
@zcei Ah, just saw your comment. I've already created a PR #83.

 @Khaledgarbaya, feel free to improve it or use it as a starting point. You know the code base much better than I do. One of the things I was thinking about is whether the logic to fetch all paginated entries is needed anywhere else. In that case, it would make sense to abstract it away.

**Comment by zcei** [comment]
No worries, that was the quick fix that he was planning to do as well.

(In mid-to-longterm I'm in favor of a side-channel to the `OfflineAPI` to hand in the entries page by page, so that huge spaces that might not fit into memory at once can be processed as well.)

Currently I don't think it's necessary at any other place. Thanks a lot for your contribution!
